In [1]:
import pandas as pd

In [2]:
import requests

url = 'https://ember.elastic.co/ember_dataset_2017_2.tar.bz2'
response = requests.get(url, stream=True)

with open('ember_dataset_2017_2.tar.bz2', 'wb') as file:
    for chunk in response.iter_content(chunk_size=8192):
        file.write(chunk)


In [3]:
import tarfile
import bz2

# Decompress and extract the tar.bz2 file
with bz2.open('ember_dataset_2017_2.tar.bz2', 'rb') as f_in, tarfile.open(fileobj=f_in, mode='r') as tar:
    tar.extractall()



In [4]:
#extracting the decompressed file
%cd C:\project
!tar -xvf ember_dataset_2017_2.tar.bz2



C:\project


C:\Users\mshee\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\IPython\core\magics\osm.py:417: UserWarning: using dhist requires you to install the `pickleshare` library.
  self.shell.db['dhist'] = compress_dhist(dhist)[-100:]


x ember_2017_2/
x ember_2017_2/train_features_1.jsonl
x ember_2017_2/train_features_0.jsonl
x ember_2017_2/train_features_3.jsonl
x ember_2017_2/test_features.jsonl
x ember_2017_2/train_features_5.jsonl
x ember_2017_2/train_features_4.jsonl
x ember_2017_2/train_features_2.jsonl


In [5]:
#vectorization
import ember


In [7]:
ember.create_vectorized_features("C:\Users\mshee\OneDrive\Desktop\proo\ember_2017_2")
ember.create_metadata("C:\Users\mshee\OneDrive\Desktop\proo\ember_2017_2")

Vectorizing training set


100%|██████████| 900000/900000 [10:46<00:00, 1392.22it/s]


Vectorizing test set


100%|██████████| 200000/200000 [02:40<00:00, 1248.21it/s]


sha256 appeared  label  \
0        0abb4fda7d5b13801d63bee53e5e256be43e141faa077a...  2006-12      0   
1        d4206650743b3d519106dea10a38a55c30467c3d9f7875...  2006-12      0   
2        c9cafff8a596ba8a80bafb4ba8ae6f2ef3329d95b85f15...  2007-01      0   
3        7f513818bcc276c531af2e641c597744da807e21cc1160...  2007-02      0   
4        ca65e1c387a4cc9e7d8a8ce12bf1bcf9f534c9032b9d95...  2007-02      0   
...                                                    ...      ...    ...   
1099995  fffe314f23cee3a68ccab272934877d3bc18ec3bd905df...  2017-12      0   
1099996  fffe7a1b23e04facc9ca91a93ac4a34e8b3040e023dbde...  2017-12      1   
1099997  fffe801f51e7ec931515aa49a3d157a9c0fbcdca8c9d80...  2017-12      0   
1099998  fffe92f9593649c4a7050302368189de45e2c1c06b04ea...  2017-12      1   
1099999  ffffb259a4c5e25ae1437af59caafb718cf8879187cc8c...  2017-12      1   

        subset  
0        train  
1        train  
2        train  
3        train  
4        train  
...        ...  
1099995   test  
1099996   test  
1099997   test  
1099998   test  
1099999   test  

[1100000 rows x 4 columns]

In [2]:
import ember
data_path = 'C:\\Users\mshee\OneDrive\Desktop\proo\ember_2017_2'
emberdf = ember.read_metadata(data_path)
emberdf.head()

sha256 appeared  label subset
0  0abb4fda7d5b13801d63bee53e5e256be43e141faa077a...  2006-12      0  train
1  d4206650743b3d519106dea10a38a55c30467c3d9f7875...  2006-12      0  train
2  c9cafff8a596ba8a80bafb4ba8ae6f2ef3329d95b85f15...  2007-01      0  train
3  7f513818bcc276c531af2e641c597744da807e21cc1160...  2007-02      0  train
4  ca65e1c387a4cc9e7d8a8ce12bf1bcf9f534c9032b9d95...  2007-02      0  train

In [3]:
X_train0, y_train0, X_test0, y_test0 = ember.read_vectorized_features(data_path)

In [4]:
X_train0

memmap([[1.4676122e-02, 4.2218715e-03, 3.9226813e-03, ..., 0.0000000e+00,
         0.0000000e+00, 0.0000000e+00],
        [7.2290748e-02, 1.4057922e-02, 1.1037279e-02, ..., 0.0000000e+00,
         0.0000000e+00, 0.0000000e+00],
        [1.8452372e-01, 3.1307504e-02, 5.6928140e-03, ..., 4.4229600e+05,
         0.0000000e+00, 0.0000000e+00],
        ...,
        [3.2558188e-01, 5.2042645e-03, 4.0974934e-03, ..., 0.0000000e+00,
         0.0000000e+00, 0.0000000e+00],
        [5.0731432e-01, 9.9041909e-03, 5.1698429e-03, ..., 0.0000000e+00,
         0.0000000e+00, 0.0000000e+00],
        [6.8576080e-01, 4.2310823e-03, 4.0683481e-03, ..., 0.0000000e+00,
         0.0000000e+00, 0.0000000e+00]], dtype=float32)

In [5]:
#shape of the dataset
X_train0.shape, y_train0.shape, X_test0.shape, y_test0.shape
#Training set: 900,000 samples, each with 2381 features.
#Training labels: 900,000 labels.
#Test set: 200,000 samples, each with 2381 features.
#Test labels: 200,000 labels.

((900000, 2381), (900000,), (200000, 2381), (200000,))

In [6]:
import pandas as pd
# Creating dataframes of X_train & y_train
X_train0 = pd.DataFrame(X_train0)
y_train0 = pd.DataFrame(y_train0)
X_train0.shape, y_train0.shape

((900000, 2381), (900000, 1))

In [7]:
#Unique labels in the train dataset
y_train0[0].unique()

array([ 0., -1.,  1.], dtype=float32)

In [8]:
# Combining features and lables of train dataset
X_train0[2381] = y_train0[0]
X_train0.shape, y_train0.shape

((900000, 2382), (900000, 1))

In [9]:
#Checking the presence of unique lables in the combined dataframe
X_train0[2381].unique()

array([ 0., -1.,  1.], dtype=float32)

In [10]:
#dropping unlabeled samples
X_train0.drop(X_train0[(X_train0[2381] == -1)].index, inplace = True)

In [11]:
y_train0.drop(y_train0[(y_train0[0] == -1)].index, inplace = True)

In [12]:
X_train0.shape, y_train0.shape

((600000, 2382), (600000, 1))

In [13]:
#reconstructing the X_train dataframe
X_train0.drop([2381], axis =1, inplace=True)
X_train0.shape, y_train0.shape

((600000, 2381), (600000, 1))

In [15]:
#Pickling the datasets
pd.DataFrame(X_train0).to_pickle("./X_train.pkl")
pd.DataFrame(y_train0).to_pickle("./y_train.pkl")
pd.DataFrame(X_test0).to_pickle("./X_test.pkl")
pd.DataFrame(y_test0).to_pickle("./y_test.pkl")

In [14]:
# Extracting training data from pickle files
X_trainp = pd.read_pickle("C:\\Users\mshee\OneDrive\Desktop\proo\X_train.pkl")
y_trainp = pd.read_pickle("C:\\Users\mshee\OneDrive\Desktop\proo\y_train.pkl")


In [15]:
# Extracting testing data from pickle files
X_testp =pd.read_pickle("C:\\Users\mshee\OneDrive\Desktop\proo\X_test.pkl")
y_testp = pd.read_pickle("C:\\Users\mshee\OneDrive\Desktop\proo\y_test.pkl")

In [16]:
#Shape of the dataset
X_trainp.shape, y_trainp.shape, X_testp.shape, y_testp.shape

((600000, 2381), (600000, 1), (200000, 2381), (200000, 1))

In [17]:
import h5py
# Loading X_train data to HDF5 file
h50 = h5py.File('X_train0.h5', 'a')
h50.create_dataset('X_train0', data=X_train0)
h50.close()

In [18]:
# Loading y_train data to HDF5 file
h51 = h5py.File('y_train0.h5', 'w')
h51.create_dataset('y_train0', data=y_train0)
h51.close()

In [19]:
#Loading X_test data to HDF5 file
h52 = h5py.File('X_test0.h5', 'w')
h52.create_dataset('X_test0', data=X_test0)
h52.close()

In [20]:
#Loading y_test data to HDF5 file
h53 = h5py.File('y_test0.h5', 'w')
h53.create_dataset('y_test0', data=y_test0)
h53.close()

In [21]:
#reading the X_train data from h5 files
import h5py
Xh5 = h5py.File('C:\\Users\mshee\OneDrive\Desktop\proo\X_train0.h5','r')
X_train = Xh5['X_train0']
X_train.shape

(600000, 2381)

In [22]:
# Reading y_train data from h5 files
import h5py
yh5 = h5py.File('C:\\Users\mshee\OneDrive\Desktop\proo\y_train0.h5','r')
y_train = yh5['y_train0']
y_train.shape

(600000, 1)

In [23]:
# Reading X_test data from h5 files
import h5py
Xth5 = h5py.File('C:\\Users\mshee\OneDrive\Desktop\proo\X_test0.h5','r')
X_test = Xth5['X_test0']
X_test.shape

(200000, 2381)

In [24]:
# Reading y_test data from h5 files
import h5py
yth5 = h5py.File('C:\\Users\mshee\OneDrive\Desktop\proo\y_test0.h5','r')
y_test = yth5['y_test0']
y_test.shape

(200000,)

In [25]:
# Scaling the features inorder to improve the performance of the model
from sklearn.preprocessing import RobustScaler
rs = RobustScaler()
Xtrain_rs = rs.fit_transform(X_train)
Xtest_rs = rs.fit_transform(X_test)

In [26]:
#Loading scaled X_train data to HDF5 file
h54 = h5py.File('Xtrain_rs.h5', 'w')
h54.create_dataset('Xtrain_rs', data=Xtrain_rs)
h54.close()



In [27]:
#Loading scaled X_test data to HDF5 file
h55 = h5py.File('Xtest_rs.h5', 'w')
h55.create_dataset('Xtest_rs', data=Xtest_rs)
h55.close()


In [28]:
# Reading Xtrain_rs data from h5 files
import h5py
Xrsh5 = h5py.File('C:\\Users\mshee\OneDrive\Desktop\proo\Xtrain_rs.h5','r')
Xtrain_rs = Xrsh5['Xtrain_rs']
Xtrain_rs.shape

(600000, 2381)

In [29]:
# Reading Xtest_rs data from h5 files
import h5py
Xtrsh5 = h5py.File('C:\\Users\mshee\OneDrive\Desktop\proo\Xtest_rs.h5','r')
Xtest_rs = Xtrsh5['Xtest_rs']
Xtest_rs.shape

(200000, 2381)

In [30]:
import numpy as np

Xtrain_rs = np.array(Xtrain_rs)
y_train = np.array(y_train)


In [64]:
# #Function for the model
# def myModel():

#     import tensorflow as tf
#     from tensorflow import keras
#     from tensorflow.keras import layers
#     from tensorflow.keras.models import Sequential
#     from keras import regularizers
#     tf.compat.v1.disable_eager_execution()

#     #Model architecture
#     model = Sequential()
#     model.add(layers.InputLayer(input_shape=(2381,)))
#     model.add(layers.Dropout(0.2))
#     model.add(layers.Dense(units = 1000, activation = tf.nn.relu, activity_regularizer=regularizers.l2(0.01)))
#     model.add(layers.Dropout(0.5))
#     model.add(layers.Dense(units = 1, activation=tf.nn.sigmoid))
#     print(model.summary())

#     #model compilation
#     model.compile(optimizer='adam', loss='binary_crossentropy', metrics=['accuracy'])

#     model.save('my_model.h5')

#    return model
def myModel():
    import tensorflow as tf
    from tensorflow.keras.models import Sequential
    from tensorflow.keras.layers import InputLayer, Dense, Dropout, BatchNormalization
    from tensorflow.keras import regularizers



    # Model architecture
    model = Sequential()
    model.add(InputLayer(input_shape=(2381,)))
    model.add(Dropout(0.5))
    model.add(Dense(units=1000, activation=tf.nn.sigmoid, activity_regularizer=regularizers.l2(0.01)))
    model.add(Dropout(0.5))
    model.add(Dense(units=512, activation=tf.nn.sigmoid))
    model.add(BatchNormalization())
    model.add(Dense(units=256, activation=tf.nn.sigmoid))
    model.add(Dense(units=1, activation=tf.nn.sigmoid))

    optimizer = tf.keras.optimizers.Adam(learning_rate=0.001) 
    model.compile(optimizer=optimizer, loss='binary_crossentropy', metrics=['accuracy'])


    return model




In [65]:
model = myModel()

In [66]:
#Training the model on 1 epoch
history = model.fit(Xtrain_rs, y_train,
                batch_size=256, shuffle="batch",
                epochs=1,
                validation_split=0.2)

1875/1875 [==============================] - 119s 62ms/step - loss: 1.6602 - accuracy: 0.5711 - val_loss: 1.1480 - val_accuracy: 0.4458


In [67]:
history = model.fit(Xtrain_rs, y_train,
                batch_size=256, shuffle="batch",
                epochs=19,
                validation_split=0.2)

Epoch 1/19
1875/1875 [==============================] - 109s 58ms/step - loss: 1.1941 - accuracy: 0.5958 - val_loss: 1.0667 - val_accuracy: 0.5590
Epoch 2/19
1875/1875 [==============================] - 116s 62ms/step - loss: 1.1376 - accuracy: 0.6006 - val_loss: 1.0064 - val_accuracy: 0.6023
Epoch 3/19
1875/1875 [==============================] - 111s 59ms/step - loss: 1.0910 - accuracy: 0.6055 - val_loss: 0.9895 - val_accuracy: 0.5025
Epoch 4/19
1875/1875 [==============================] - 99s 53ms/step - loss: 1.0769 - accuracy: 0.6095 - val_loss: 0.9757 - val_accuracy: 0.5143
Epoch 5/19
1875/1875 [==============================] - 99s 53ms/step - loss: 1.0557 - accuracy: 0.6138 - val_loss: 0.9846 - val_accuracy: 0.4176
Epoch 6/19
1875/1875 [==============================] - 100s 53ms/step - loss: 1.0327 - accuracy: 0.6166 - val_loss: 0.9687 - val_accuracy: 0.5406
Epoch 7/19
1875/1875 [==============================] - 101s 54ms/step - loss: 1.0115 - accuracy: 0.6176 - val_loss: 0.9

In [ ]:
# testing the model

score =model.evaluate(Xtest_rs,y_test)
print("Accuracy:", score[1])

In [37]:
# Save the model
model.save('model.h5')
model.save_weights('model_weights.h5')


In [38]:
# save neural network structure to JSON (no weights)
model_json = model.to_json()
with open("mymodeljson.json", "w") as json_file:
    json_file.write(model_json)

model.save_weights("model-weights.h5")

In [1]:
import requests

url = 'https://repo.anaconda.com/archive/Anaconda3-2020.02-Windows-x86_64.exe'
file_name = 'Anaconda3-2020.02-Windows-x86_64.exe'

response = requests.get(url)

if response.status_code == 200:
    with open(file_name, 'wb') as f:
        f.write(response.content)
    print(f"File '{file_name}' downloaded successfully.")
else:
    print("Failed to download the file.")


File 'Anaconda3-2020.02-Windows-x86_64.exe' downloaded successfully.


In [39]:
import ember

In [2]:
def testPE(pe):
  import ember
  import numpy as np
  import tensorflow as tf
  from sklearn.preprocessing import RobustScaler
  rs = RobustScaler()

  #opening the downloaded PE file
  testpe = open(pe, "rb").read()
  #Feature extractor class of the ember project
  extract = ember.PEFeatureExtractor()
  data = extract.feature_vector(testpe) #vectorizing the extracted features
  scaled_data = rs.fit_transform([data])
  Xdata = np.reshape(scaled_data,(1, 2381))

  model = tf.keras.models.load_model('my_model.h5')
  pred_probabilities = model.predict(Xdata)
  pred_classes = np.argmax(pred_probabilities, axis=1)

  if pred_classes == 0:
        return "benign"
  elif pred_classes == 1:
        return "malware"
  #return pred_classes

In [3]:
testPE("Anaconda3-2020.02-Windows-x86_64.exe")




1/1 [==============================] - 0s 232ms/step


array([0], dtype=int64)

In [4]:
testPE("Git-2.43.0-64-bit.exe")

1/1 [==============================] - 0s 163ms/step


array([0], dtype=int64)

In [5]:
testPE("GrammarlyInstaller.cVWGUea8qwif8kgejq0p01o2.exe")

1/1 [==============================] - 0s 98ms/step


array([0], dtype=int64)